use restapi;

INSERT INTO product_category(category_name) VALUES ('Indoor plants');
INSERT INTO product_category(category_name) VALUES ('Photo Frames');
INSERT INTO product_category(category_name) VALUES ('Wall Prints');
INSERT INTO product_category(category_name) VALUES ('Timber Decors');
INSERT INTO product_category(category_name) VALUES ('Ceiling Decors');

-- -----------------------------------------------------
-- Indoor plants
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1000', 'Plant-1', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1000.png', 1, 100, 399, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1001', 'Plant-2', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1001.png', 1, 100, 599, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1002', 'Plant-3', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1002.png', 1, 100, 799, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1003', 'Plant-4', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1003.png', 1, 100, 499, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1004', 'Plnat-5', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1004.png', 1, 100, 799, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1005', 'Plant-6', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1005.png', 1, 100, 699, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1006', 'Plant-7', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1006.png', 1, 100, 999, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1007', 'Plant-8', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1007.png', 1, 100, 1999, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1008', 'Plant-9', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1008.png', 1, 100, 799, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1009', 'Plant-10', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1009.png', 1, 100, 499, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1010', 'Plant-11', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1010.png', 1, 100, 399, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1011', 'Plant-12', 'These plants need low maintenance. These plants will come in a 1-inch net pot. Please do not remove the plant from the net pot and directly repot it in a larger pot with the net pot. Do not overwater the plant.', 'assets/images/products/Furniture/book-luv2code-1011.png', 1, 100, 999, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1012', 'Plant-13', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1012.png', 1, 100, 799, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1013', 'Plant-14', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1013.png', 1, 100, 999, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1014', 'Plant-15', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming.', 'assets/images/products/Furniture/book-luv2code-1014.png', 1, 100, 399, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1015', 'Plant-16', ' Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1015.png', 1, 100, 499, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1016', 'Plant-17', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1016.png', 1, 100, 899, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1017', 'Plant-18', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1017.png', 1, 100, 999, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1018', 'Plant-19', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming.', 'assets/images/products/Furniture/book-luv2code-1018.png', 1, 100, 399, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1019', 'Plant-20', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1019.png', 1, 100, 499, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1020', 'Plant-21', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1020.png', 1, 100, 699, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1021', 'Plant-22', 'Blooming blossoming; flowering; flourishing; thriving in vigor, health and beauty. Blossoming the process and time of budding and unfolding of blossoms. Blushing having a delicate and warm color like some flowers; roseate; blooming', 'assets/images/products/Furniture/book-luv2code-1021.png', 1, 100, 1499, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1022', 'Plant-23', 'Indoor Plants eliminate toxins from the air, improving our home air quality. They are energizing for the mind by lowering our stress levels and encouraging a deeper sleep. As the say goes; “Plants make people happy', 'assets/images/products/Furniture/book-luv2code-1022.png', 1, 100, 199, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1023', 'Plant-24', 'Indoor Plants eliminate toxins from the air, improving our home air quality. They are energizing for the mind by lowering our stress levels and encouraging a deeper sleep. As the say goes; “Plants make people happy', 'assets/images/products/Furniture/book-luv2code-1023.png', 1, 100, 99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1024', 'Plant-25', 'Indoor Plants eliminate toxins from the air, improving our home air quality. They are energizing for the mind by lowering our stress levels and encouraging a deeper sleep. As the say goes; “Plants make people happy', 'assets/images/products/Furniture/book-luv2code-1024.png', 1, 100, 599, 1, NOW());

-- -----------------------------------------------------
-- Photo Frames
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1000', 'Frame-1', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1000.png', 1, 100, 1000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1001', 'Frame-2', ' The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1001.png', 1, 100, 2000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1002', 'Frame-3', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1002.png', 1, 100, 4000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1003', 'Frame-4', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1003.png', 1, 100, 1500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1004', 'Frame-5', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1004.png', 1, 100, 1600, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1005', 'Frame-6', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come.', 'assets/images/products/coffeemugs/coffeemug-luv2code-1005.png', 1, 100, 1200, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1006', 'Frame-7', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1006.png', 1, 100, 2500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1007', 'Frame-8', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1007.png', 1, 100, 5000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1008', 'Frame-9', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1008.png', 1, 100, 1600, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1009', 'Frame-10', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1009.png', 1, 100, 1400, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1010', 'Frame-11', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1010.png', 1, 100, 1000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1011', 'Frame-12', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1011.png', 1, 100, 3000, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1012', 'Frame-13', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1012.png', 1, 100, 3500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1013', 'Frame-14', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1013.png', 1, 100, 1800, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1014', 'Frame-15', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1014.png', 1, 100, 1500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1015', 'Frame-16', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1015.png', 1, 100, 2600, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1016', 'Frame-17', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1016.png', 1, 100, 2200, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1017', 'Frame-18', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1017.png', 1, 100, 2100, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1018', 'Frame-19', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1018.png', 1, 100, 1400, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1019', 'Frame-20', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1019.png', 1, 100, 3200, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1020', 'Frame-21', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1020.png', 1, 100, 1400, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1021', 'Frame-22', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1021.png', 1, 100, 2500, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1022', 'Frame-22', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1022.png', 1, 100, 3600, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1023', 'Frame-23', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1023.png', 1, 100, 3700, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1024', 'Frame-24', 'The artistic decorative patterns and graphics are laser engraved on a stunning MDF wood frame with non – reflective glass and then personalized with your first names , for a lasting and memorable keep sake for years to come., guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1024.png', 1, 100, 2800, 2, NOW());

-- -----------------------------------------------------
-- Wall Prints
-- -----------------------------------------------------



INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1000', 'Wall Print-1', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply. ', 'assets/images/products/mousepads/mousepad-luv2code-1000.png', 1, 100, 599, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1001', 'Wall Print-2', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1001.png', 1, 100, 899, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1002', 'Wall Print-3', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1002.png', 1, 100, 1500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1003', 'Wall Print-4', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1003.png', 1, 100, 1600, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1004', 'Wall Print-5', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1004.png', 1, 100, 2000, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1005', 'Wall Print-6', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1005.png', 1, 100, 999, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1006', 'Wall Print-7', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1006.png', 1, 100, 1600, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1007', 'Wall Print-8', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1007.png', 1, 100, 1789, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1008', 'Wall Print-9', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1008.png', 1, 100, 1799, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1009', 'Wall Print-10', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1009.png', 1, 100, 2500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1010', 'Wall Print-11', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1010.png', 1, 100, 1500, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1011', 'Wall Print-12', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1011.png', 1, 100, 1300, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1012', 'Wall Print-13', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1012.png', 1, 100, 1800, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1013', 'Wall Print-14', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1013.png', 1, 100, 1900, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1014', 'Wall Print-15', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1014.png', 1, 100, 799, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1015', 'Wall Print-16', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1015.png', 1, 100, 899, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1016', 'Wall Print-17', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1016.png', 1, 100, 599, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1017', 'Wall Print-18', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1017.png', 1, 100, 499, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1018', 'Wall Print-19', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1018.png', 1, 100, 1400, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1019', 'Wall Print-20', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1019.png', 1, 100, 1700, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1020', 'Wall Print-21', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1020.png', 1, 100, 1799, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1021', 'Wall Print-21', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1021.png', 1, 100, 1759, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1022', 'Wall Print-22', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1022.png', 1, 100, 1900, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1023', 'Wall Print-23', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1023.png', 1, 100, 1700, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MOUSEPAD-1024', 'Wall Print-24', 'wall decals and wall stickers are self-adhesive vinyl stickers made for applying to a surface.they are a great alternative to wallpaper, paint or stencils and they give you choice. Choose your space, plan the design you like to make, and then apply.', 'assets/images/products/mousepads/mousepad-luv2code-1024.png', 1, 100, 2400, 3, NOW());

-- -----------------------------------------------------
-- Timber Decors
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1000', 'Timber Decor-1', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1000.png', 1, 100, 4999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1001', 'Timber Decor-2', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1001.png', 1, 100, 5999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1002', 'Timber Decor-3', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1002.png', 1, 100, 7999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1003', 'Timber Decor-4', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1003.png', 1, 100, 5999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1004', 'Timber Decor-5', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1004.png', 1, 100, 8888, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1005', 'Timber Decor-6', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1005.png', 1, 100, 6000, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1006', 'Timber Decor-7', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1006.png', 1, 100, 3000, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1007', 'Timber Decor-8', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1007.png', 1, 100, 3999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1008', 'Timber Decor-9', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1008.png', 1, 100, 4999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1009', 'Timber Decor-10', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1009.png', 1, 100, 4000, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1010', 'Timber Decor-11', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1010.png', 1, 100, 2999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1011', 'Timber Decor-12', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1011.png', 1, 100, 1000, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1012', 'Timber Decor-13', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1012.png', 1, 100, 8999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1013', 'Timber Decor-14', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1013.png', 1, 100, 9999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1014', 'Timber Decor-15', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1014.png', 1, 100, 7999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1015', 'Timber Decor-16', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1015.png', 1, 100, 6999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1016', 'Timber Decor-17', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1016.png', 1, 100, 1599, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1017', 'Timber Decor-18', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1017.png', 1, 100, 2999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1018', 'Timber Decor-19', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1018.png', 1, 100, 5999, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1019', 'Timber Decor-20', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1019.png', 1, 100, 2600, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1020', 'Timber Decor-21', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1020.png', 1, 100, 3400, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1021', 'Timber Decor-22', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1021.png', 1, 100, 2800, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1022', 'Timber Decor-23', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1022.png', 1, 100, 9800, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1023', 'Timber Decor-24', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1023.png', 1, 100, 6400, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1024', 'Timber Decor-25', 'Timber Boarding is where boards are laid side by side with rebates or moldings on each edge so that the straight tongue on one (matches) the groove on the other.', 'assets/images/products/luggagetags/luggagetag-luv2code-1024.png', 1, 100, 4500, 4, NOW());

-- -----------------------------------------------------
-- Ceiling Decors
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1000', 'Ceiling Decor-1', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor1.jfif', 1, 100, 3000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1001', 'Ceiling Decor-2', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor2.jfif', 1, 100, 2000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1002', 'Ceiling Decor-3', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor3.jfif', 1, 100, 4000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1003', 'Ceiling Decor-4', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor4.jfif', 1, 100, 2500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1004', 'Ceiling Decor-5', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor5.jfif', 1, 100, 3100, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1005', 'Ceiling Decor-6', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor6.jfif', 1, 100, 5100, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1006', 'Ceiling Decor-7', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor7.jfif', 1, 100, 1500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1007', 'Ceiling Decor-8', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor8.jfif', 1, 100, 799, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1008', 'Ceiling Decor-9', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor9.jfif', 1, 100, 5300, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1009', 'Ceiling Decor-10', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor15.jfif', 1, 100, 1000, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1010', 'Ceiling Decor-11', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor11.jfif', 1, 100, 3500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1011', 'Ceiling Decor-12', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor12.jfif', 1, 100, 5400, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1012', 'Ceiling Decor-13', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor13.jfif', 1, 100, 1400, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1013', 'Ceiling Decor-14', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor14.jfif', 1, 100, 3500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1014', 'Ceiling Decor-15', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor15.jfif', 1, 100, 2500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1015', 'Ceiling Decor-16', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor16.jfif', 1, 100, 4500, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1016', 'Ceiling Decor-17', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor17.jfif', 1, 100, 1400, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1017', 'Ceiling Decor-18', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor18.jfif', 1, 100, 5400, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1018', 'Ceiling Decor-19', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor19.jfif', 1, 100, 2600, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LUGGAGETAG-1019', 'Ceiling Decor-20', 'wind chimes can be metal, glass, plastic, wood (woodstock wind chimes), or combinations of them, and even other materials. Some of these materials speak to us more than others, with some seeming rather unlikely to many individuals.', 'assets/images/products/Ceiling Decors/decor20.jfif', 1, 100, 4500, 5, NOW());
